User.php: This seems to fix bug 91
Fatal error: Call to a member function get() on a non-object in User.php on line 90
https://github.com/jeromeschneider/Baikal/issues/91

however, I don't know whether this breaks anything.
It seems to work well enough for me.


Former-commit-id: 9818e4fdbf99210f624e6e41f8de863ada4c123a